### ISSUE TITLE
fatal: reference is not a tree: 7f2d304fda282aee48ffd45d369afee4f75a145d

### ISSUE THREAD

**Issue by adam-young-dev** [MeshJS/mesh.plutus#1]
Try to build from: https://github.com/MartifyLabs/mesh.plutus/tree/always-true
Then get the error:
fatal: reference is not a tree: 7f2d304fda282aee48ffd45d369afee4f75a145d

Seems like that tag doesn't exist.
Try a different tag (tag:4edc082309c882736e9dec0132a3c936fe63b4ea) but get a different error.

**Comment by AlainMgz** [comment]
Hey, really sorry for the late reply. I just pushed a fix, try it and let me know :)

**Comment by adam-young-dev** [comment]
It works now. Thanks!
